export const TEXTS = {
  en: {
    placeholder: 'Type something or speak...',
    listening: 'Listening...',
    thinking: 'Thinking...',
    speaking: 'Speaking...',
    configSaved: 'Configuration saved!',
    configSaveError: 'Error saving configuration',
    enterConfigFirst: 'Please configure your Gemini API key first',
    errorGettingResponse: 'Error getting AI response',
    recognitionNotSupported: 'Speech recognition is not supported in this browser',
    errorStartingRecognition: 'Error starting speech recognition',
    youSaid: 'You said: ',
    aiResponseObtained: 'Got response',
    configTitle: 'Configure Gemini',
    configWarning: 'API key stored securely in your Google Drive.',
    configWarningGuest: 'API key stored in browser localStorage.',
    configWarningDriveUnavailable: 'Google Drive unavailable. Config stored in browser only.',
    cameraPermissionDenied: 'Camera permission denied. Continuing without face recognition.',
    trainingInProgress: 'Hold still... Capturing {current} of {total}',
    trainingComplete: 'Face training complete!',
    trainingFailed: 'Face training failed. Please try again.',
    faceRecognized: 'Welcome back, {name}!',
    faceUnknown: 'Face not recognized.',
    systemPrompt: `You are Cognitive Avatar (CGA), a friendly and knowledgeable AI research assistant. You help users learn, investigate, and understand any topic. You speak naturally and conversationally, like a knowledgeable friend. When you don't know something, say so honestly and offer to help the user find the answer. You can reference information from web sources if provided. You are a voice-first interactive guide for CognitiveOS. You are communicating via a basic text-to-speech engine. You MUST adhere strictly to these rules for every single response: 1. EXTREME BREVITY: Never exceed 2 to 3 short sentences. Get straight to the point. 2. NO FORMATTING: Never use bullet points, numbered lists, asterisks, bolding, brackets, or markdown of any kind. 3. CONVERSATIONAL PACING: Write exactly how a human speaks. Use commas to create natural pauses for the voice synthesizer. 4. THE CHUNKING RULE: If a user asks a complex technical question, give a one-sentence high-level summary, and then ask a follow-up question like: "Would you like me to explain how that works in detail?"`,
    onboardingGreeting: "Hello, I'm Cognitive Avatar! May I have your name?",
    onboardingAskCamera: "Nice to meet you, {name}! I'd like to recognize you in future sessions. May I use the camera?",
    onboardingTraining: "Hold still, I'm taking {count} photos...",
    onboardingComplete: "Thank you, {name}! Now, what do you want to learn or investigate today!",
    onboardingFailed: "I couldn't capture your face clearly. Let's try again.",
    faceDetectHint: "I'm having trouble seeing your face. Try moving closer or check the lighting.",
    faceDetectTimeout: "I couldn't detect your face in time. Let's continue without face recognition.",
    cameraReady: 'Camera active',
    cameraOff: 'Camera off',
    stopped: 'Stopped',
    repeated: 'Repeating...',
    cleared: 'Cleared',
  },
  es: {
    placeholder: 'Escribe algo o habla...',
    listening: 'Escuchando...',
    thinking: 'Pensando...',
    speaking: 'Hablando...',
    configSaved: '¡Configuración guardada!',
    configSaveError: 'Error al guardar configuración',
    enterConfigFirst: 'Por favor configura tu clave API de Gemini primero',
    errorGettingResponse: 'Error al obtener respuesta de IA',
    recognitionNotSupported: 'El reconocimiento de voz no es compatible con este navegador',
    errorStartingRecognition: 'Error al iniciar reconocimiento de voz',
    youSaid: 'Dijiste: ',
    aiResponseObtained: 'Respuesta obtenida',
    configTitle: 'Configurar Gemini',
    configWarning: 'Clave API guardada de forma segura en tu Google Drive.',
    configWarningGuest: 'Clave API guardada en almacenamiento local del navegador.',
    configWarningDriveUnavailable: 'Google Drive no disponible. Config guardada en navegador.',
    cameraPermissionDenied: 'Permiso de cámara denegado. Continuando sin reconocimiento facial.',
    trainingInProgress: 'No te muevas... Capturando {current} de {total}',
    trainingComplete: '¡Entrenamiento facial completo!',
    trainingFailed: 'Error en entrenamiento facial. Por favor intenta de nuevo.',
    faceRecognized: '¡Bienvenido de nuevo, {name}!',
    faceUnknown: 'Rostro no reconocido.',
    systemPrompt: `Eres Cognitive Avatar (CGA), un amigable y conocedor asistente de investigación con IA. Ayudas a los usuarios a aprender, investigar y entender cualquier tema. Hablas de forma natural y conversacional, como un amigo conocedor. Cuando no sepas algo, dilo honestamente y ofrece ayudar al usuario a encontrar la respuesta. Puedes referirte a información de fuentes web si se proporciona. Eres una guía interactiva de CognitiveOS, optimizada para voz. Comunicas a través de un motor de texto a voz básico. Debes adherirte estrictamente a estas reglas en cada respuesta: 1. EXTREMA BREVEDAD: Nunca excedas 2 a 3 oraciones cortas. Ve directo al punto. 2. SIN FORMATO: Nunca uses viñetas, listas numeradas, asteriscos, negritas, corchetes ni ningún tipo de markdown. 3. RITMO CONVERSACIONAL: Escribe exactamente como habla un humano. Usa comas para crear pausas naturales para el sintetizador de voz. 4. REGLA DE FRAGMENTACIÓN: Si el usuario hace una pregunta técnica compleja, da un resumen alto de una oración, y luego haz una pregunta de seguimiento como: "¿Te gustaría que te explique cómo funciona en detalle?"`,
    onboardingGreeting: "¡Hola, soy Cognitive Avatar! ¿Cómo te llamas?",
    onboardingAskCamera: "¡Encantado de conocerte, {name}! Me gustaría reconocerte en futuras sesiones. ¿Puedo usar la cámara?",
    onboardingTraining: "No te muevas, estoy tomando {count} fotos...",
    onboardingComplete: "¡Gracias, {name}! Ahora, ¿qué quieres aprender o investigar hoy!",
    onboardingFailed: "No pude capturar tu rostro claramente. Intentemos de nuevo.",
    faceDetectHint: "Tengo problemas para ver tu rostro. Acércate más o verifica la iluminación.",
    faceDetectTimeout: "No pude detectar tu rostro a tiempo. Continuemos sin reconocimiento facial.",
    cameraReady: 'Cámara activa',
    cameraOff: 'Cámara apagada',
    stopped: 'Detenido',
    repeated: 'Repitiendo...',
    cleared: 'Borrado',
  },
};
