export const TEXTS = {
  en: {
    placeholder: 'Type something or speak...',
    speakButton: 'Speak',
    stopButton: 'Stop',
    showSettings: 'Show Settings',
    hideSettings: 'Hide Settings',
    english: 'English',
    spanish: 'Spanish',
    listening: 'Listening...',
    thinking: 'Thinking...',
    speaking: 'Speaking...',
    configSaved: 'Configuration saved!',
    configSaveError: 'Error saving configuration',
    enterConfigFirst: 'Please configure your Azure OpenAI settings first',
    errorGettingResponse: 'Error getting AI response',
    recognitionNotSupported: 'Speech recognition is not supported in this browser',
    errorStartingRecognition: 'Error starting speech recognition',
    youSaid: 'You said: ',
    aiResponseObtained: 'Got response',
    configTitle: 'Configure Azure OpenAI',
    configWarning: 'API key stored securely in your Google Drive.',
    configWarningGuest: 'API key stored in browser localStorage.',
    configWarningDriveUnavailable: 'Google Drive unavailable. Config stored in browser only.',
    cameraPermissionDenied: 'Camera permission denied. Continuing without face recognition.',
    trainingInProgress: 'Hold still... Capturing {current} of {total}',
    trainingComplete: 'Face training complete!',
    trainingFailed: 'Face training failed. Please try again.',
    faceRecognized: 'Welcome back, {name}!',
    faceUnknown: 'Face not recognized.',
    systemPrompt: `You are Cognitive Avatar (CGA), a friendly and knowledgeable AI research assistant. You help users learn, investigate, and understand any topic. You speak naturally and conversationally, like a knowledgeable friend. Keep responses concise and clear for voice interaction. When you don't know something, say so honestly and offer to help the user find the answer. You can reference information from web sources if provided.`,
    onboardingGreeting: "Hello, I'm Cognitive Avatar! May I have your name?",
    onboardingAskCamera: "Nice to meet you, {name}! I'd like to recognize you in future sessions. May I use the camera?",
    onboardingTraining: "Hold still, I'm taking {count} photos...",
    onboardingComplete: "Thank you, {name}! Now, what do you want to learn or investigate today!",
    onboardingFailed: "I couldn't capture your face clearly. Let's try again.",
    faceDetectHint: "I'm having trouble seeing your face. Try moving closer or check the lighting.",
    faceDetectTimeout: "I couldn't detect your face in time. Let's continue without face recognition.",
    cameraReady: 'Camera active',
    cameraOff: 'Camera off',
  },
  es: {
    placeholder: 'Escribe algo o habla...',
    speakButton: 'Hablar',
    stopButton: 'Parar',
    showSettings: 'Mostrar Configuración',
    hideSettings: 'Ocultar Configuración',
    english: 'Inglés',
    spanish: 'Español',
    listening: 'Escuchando...',
    thinking: 'Pensando...',
    speaking: 'Hablando...',
    configSaved: '¡Configuración guardada!',
    configSaveError: 'Error al guardar configuración',
    enterConfigFirst: 'Por favor configura tu Azure OpenAI primero',
    errorGettingResponse: 'Error al obtener respuesta de IA',
    recognitionNotSupported: 'El reconocimiento de voz no es compatible con este navegador',
    errorStartingRecognition: 'Error al iniciar reconocimiento de voz',
    youSaid: 'Dijiste: ',
    aiResponseObtained: 'Respuesta obtenida',
    configTitle: 'Configurar Azure OpenAI',
    configWarning: 'Clave API guardada de forma segura en tu Google Drive.',
    configWarningGuest: 'Clave API guardada en almacenamiento local del navegador.',
    configWarningDriveUnavailable: 'Google Drive no disponible. Config guardada en navegador.',
    cameraPermissionDenied: 'Permiso de cámara denegado. Continuando sin reconocimiento facial.',
    trainingInProgress: 'No te muevas... Capturando {current} de {total}',
    trainingComplete: '¡Entrenamiento facial completo!',
    trainingFailed: 'Error en entrenamiento facial. Por favor intenta de nuevo.',
    faceRecognized: '¡Bienvenido de nuevo, {name}!',
    faceUnknown: 'Rostro no reconocido.',
    systemPrompt: `Eres Cognitive Avatar (CGA), un amigable y conocedor asistente de investigación con IA. Ayudas a los usuarios a aprender, investigar y entender cualquier tema. Hablas de forma natural y conversacional, como un amigo conocedor. Mantén las respuestas concisas y claras para interacción por voz. Cuando no sepas algo, dilo honestamente y ofrece ayudar al usuario a encontrar la respuesta. Puedes referirte a información de fuentes web si se proporciona.`,
    onboardingGreeting: "¡Hola, soy Cognitive Avatar! ¿Cómo te llamas?",
    onboardingAskCamera: "¡Encantado de conocerte, {name}! Me gustaría reconocerte en futuras sesiones. ¿Puedo usar la cámara?",
    onboardingTraining: "No te muevas, estoy tomando {count} fotos...",
    onboardingComplete: "¡Gracias, {name}! Ahora, ¿qué quieres aprender o investigar hoy!",
    onboardingFailed: "No pude capturar tu rostro claramente. Intentemos de nuevo.",
    faceDetectHint: "Tengo problemas para ver tu rostro. Acércate más o verifica la iluminación.",
    faceDetectTimeout: "No pude detectar tu rostro a tiempo. Continuemos sin reconocimiento facial.",
    cameraReady: 'Cámara activa',
    cameraOff: 'Cámara apagada',
  },
};
